# Generated by Django 2.0.8 on 2019-07-10 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('remark', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, default='0', max_length=64, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('remark', models.TextField()),
                ('price', models.CharField(blank=True, default='0', max_length=32, null=True)),
                ('idc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IDC_RACK', to='cmdb.Idc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('remark', models.TextField()),
                ('cpu', models.IntegerField(default='2', max_length=24)),
                ('rack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RACK_SEVER', to='cmdb.Rack')),
                ('user', models.ManyToManyField(default='', null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
