# Generated by Django 2.0.8 on 2019-07-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='numb',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='size',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
