# Generated by Django 2.0.8 on 2019-07-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20190713_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'ordering': ['id']},
        ),
    ]
