# Generated by Django 2.0.8 on 2019-07-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20190713_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='price',
        ),
    ]
