# Generated by Django 2.0.8 on 2019-07-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_remove_rack_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='user',
        ),
        migrations.AddField(
            model_name='server',
            name='business',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='业务线'),
        ),
        migrations.AddField(
            model_name='server',
            name='daq',
            field=models.TextField(blank=True, default='', null=True, verbose_name='数据采集'),
        ),
        migrations.AddField(
            model_name='server',
            name='disk',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='磁盘'),
        ),
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='server',
            name='memory',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='内存'),
        ),
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='服务器类型'),
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.IntegerField(choices=[(0, '下线'), (1, '在线')], default=1, verbose_name='运行状态'),
        ),
        migrations.AddField(
            model_name='server',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='server',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RACK_SEVER', to='cmdb.Rack', verbose_name='所属机柜'),
        ),
    ]
