# Generated by Django 2.0.8 on 2019-07-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20190715_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['id']},
        ),
    ]
