# Generated by Django 2.0.8 on 2019-07-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20190717_2314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='idc',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('name',)},
        ),
    ]
