# Generated by Django 2.0.8 on 2019-07-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20190717_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together=set(),
        ),
    ]
